# Generated by Django 4.2 on 2024-12-27 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='univer_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'doc', 'pdf'])])),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=120)),
            ],
        ),
    ]
