# Generated by Django 4.2 on 2024-12-27 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('longitute', models.CharField(max_length=120)),
                ('langitute', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='contact_info/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'web', 'png', 'jpeg'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('degree', models.CharField(choices=[('bacholor', 'Bacholor'), ('magistratura', 'Magistratura')], max_length=120)),
                ('description', models.TextField()),
                ('is_grant', models.BooleanField(default=False)),
                ('requirements', models.TextField()),
                ('education_lang', models.ManyToManyField(to='university.educationlanguage')),
                ('price_faculty_type', models.ManyToManyField(to='university.pricefaculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='univer_direction/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'web', 'png', 'jpeg'])])),
                ('university_faculty', models.ManyToManyField(to='university.universityfaculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('univer_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('international', 'International')], max_length=120)),
                ('date_registration', models.DateTimeField()),
                ('contract_sum_range', models.CharField(max_length=120)),
                ('license_pdf', models.FileField(upload_to='univer_license/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc'])])),
                ('description', models.TextField()),
                ('grand_description', models.TextField()),
                ('logo', models.ImageField(upload_to='univer_logo/')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='university.contactinfo')),
                ('media_file', models.ManyToManyField(to='common.media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='university.socialmedia'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='univer_info',
            field=models.ManyToManyField(to='university.contactinfodetail'),
        ),
    ]
